/* Generated By:JavaCC: Do not edit this line. SqlParserConstants.java */
package com.relationaljunction.jdbc.common.h2.sql;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_ALL = 11;
  /** RegularExpression Id. */
  int K_ALIAS = 12;
  /** RegularExpression Id. */
  int K_ALTER = 13;
  /** RegularExpression Id. */
  int K_ADD = 14;
  /** RegularExpression Id. */
  int K_ANALIZE = 15;
  /** RegularExpression Id. */
  int K_AND = 16;
  /** RegularExpression Id. */
  int K_ANY = 17;
  /** RegularExpression Id. */
  int K_AS = 18;
  /** RegularExpression Id. */
  int K_ASC = 19;
  /** RegularExpression Id. */
  int K_BETWEEN = 20;
  /** RegularExpression Id. */
  int K_BY = 21;
  /** RegularExpression Id. */
  int K_CALL = 22;
  /** RegularExpression Id. */
  int K_CASCADE = 23;
  /** RegularExpression Id. */
  int K_CASE = 24;
  /** RegularExpression Id. */
  int K_CAST = 25;
  /** RegularExpression Id. */
  int K_CHAINED = 26;
  /** RegularExpression Id. */
  int K_CHECK = 27;
  /** RegularExpression Id. */
  int K_CLUSTER = 28;
  /** RegularExpression Id. */
  int K_CLUSTERED = 29;
  /** RegularExpression Id. */
  int K_COLLATE = 30;
  /** RegularExpression Id. */
  int K_COLUMN = 31;
  /** RegularExpression Id. */
  int K_COLUMNS = 32;
  /** RegularExpression Id. */
  int K_COMPUTE = 33;
  /** RegularExpression Id. */
  int K_CONSTRAINT = 34;
  /** RegularExpression Id. */
  int K_CONSUMERS = 35;
  /** RegularExpression Id. */
  int K_CREATE = 36;
  /** RegularExpression Id. */
  int K_CROSS = 37;
  /** RegularExpression Id. */
  int K_DATABASE = 38;
  /** RegularExpression Id. */
  int K_DATEADD = 39;
  /** RegularExpression Id. */
  int K_DATEDIFF = 40;
  /** RegularExpression Id. */
  int K_DEFAULT = 41;
  /** RegularExpression Id. */
  int K_DELETE = 42;
  /** RegularExpression Id. */
  int K_DESC = 43;
  /** RegularExpression Id. */
  int K_DESCRIPTOR = 44;
  /** RegularExpression Id. */
  int K_DISTINCT = 45;
  /** RegularExpression Id. */
  int K_DROP = 46;
  /** RegularExpression Id. */
  int K_ELSE = 47;
  /** RegularExpression Id. */
  int K_END = 48;
  /** RegularExpression Id. */
  int K_ESTIMATE = 49;
  /** RegularExpression Id. */
  int K_EXCEPT = 50;
  /** RegularExpression Id. */
  int K_EXEC = 51;
  /** RegularExpression Id. */
  int K_EXECUTE = 52;
  /** RegularExpression Id. */
  int K_EXISTS = 53;
  /** RegularExpression Id. */
  int K_FOREIGN = 54;
  /** RegularExpression Id. */
  int K_FROM = 55;
  /** RegularExpression Id. */
  int K_FULL = 56;
  /** RegularExpression Id. */
  int K_FULLSCAN = 57;
  /** RegularExpression Id. */
  int K_GO = 58;
  /** RegularExpression Id. */
  int K_GROUP = 59;
  /** RegularExpression Id. */
  int K_HAVING = 60;
  /** RegularExpression Id. */
  int K_IMMEDIATE = 61;
  /** RegularExpression Id. */
  int K_IF = 62;
  /** RegularExpression Id. */
  int K_IN = 63;
  /** RegularExpression Id. */
  int K_INDEX = 64;
  /** RegularExpression Id. */
  int K_INDICATOR = 65;
  /** RegularExpression Id. */
  int K_INNER = 66;
  /** RegularExpression Id. */
  int K_INSERT = 67;
  /** RegularExpression Id. */
  int K_INTO = 68;
  /** RegularExpression Id. */
  int K_IS = 69;
  /** RegularExpression Id. */
  int K_JOIN = 70;
  /** RegularExpression Id. */
  int K_KEY = 71;
  /** RegularExpression Id. */
  int K_LIKE = 72;
  /** RegularExpression Id. */
  int K_LIST = 73;
  /** RegularExpression Id. */
  int K_LEFT = 74;
  /** RegularExpression Id. */
  int K_LOCK = 75;
  /** RegularExpression Id. */
  int K_MINUS = 76;
  /** RegularExpression Id. */
  int K_NATURAL = 77;
  /** RegularExpression Id. */
  int K_NONCLUSTERED = 78;
  /** RegularExpression Id. */
  int K_NOT = 79;
  /** RegularExpression Id. */
  int K_NORECOMPUTE = 80;
  /** RegularExpression Id. */
  int K_NULL = 81;
  /** RegularExpression Id. */
  int K_ON = 82;
  /** RegularExpression Id. */
  int K_OR = 83;
  /** RegularExpression Id. */
  int K_ORDER = 84;
  /** RegularExpression Id. */
  int K_OUT = 85;
  /** RegularExpression Id. */
  int K_OUTER = 86;
  /** RegularExpression Id. */
  int K_PARTITION = 87;
  /** RegularExpression Id. */
  int K_PERCENT = 88;
  /** RegularExpression Id. */
  int K_PRIMARY = 89;
  /** RegularExpression Id. */
  int K_RECOMPILE = 90;
  /** RegularExpression Id. */
  int K_REFERENCES = 91;
  /** RegularExpression Id. */
  int K_RESAMPLE = 92;
  /** RegularExpression Id. */
  int K_RIGHT = 93;
  /** RegularExpression Id. */
  int K_ROWS = 94;
  /** RegularExpression Id. */
  int K_SAMPLE = 95;
  /** RegularExpression Id. */
  int K_SELECT = 96;
  /** RegularExpression Id. */
  int K_SET = 97;
  /** RegularExpression Id. */
  int K_SHUTDOWN = 98;
  /** RegularExpression Id. */
  int K_SOME = 99;
  /** RegularExpression Id. */
  int K_STATISTICS = 100;
  /** RegularExpression Id. */
  int K_STRUCTURE = 101;
  /** RegularExpression Id. */
  int K_TABLE = 102;
  /** RegularExpression Id. */
  int K_THEN = 103;
  /** RegularExpression Id. */
  int K_TO = 104;
  /** RegularExpression Id. */
  int K_UNION = 105;
  /** RegularExpression Id. */
  int K_UNIQUE = 106;
  /** RegularExpression Id. */
  int K_UNLOCK = 107;
  /** RegularExpression Id. */
  int K_UPDATE = 108;
  /** RegularExpression Id. */
  int K_USING = 109;
  /** RegularExpression Id. */
  int K_VALIDATE = 110;
  /** RegularExpression Id. */
  int K_VALUES = 111;
  /** RegularExpression Id. */
  int K_VIEW = 112;
  /** RegularExpression Id. */
  int K_WHEN = 113;
  /** RegularExpression Id. */
  int K_WHERE = 114;
  /** RegularExpression Id. */
  int K_WITH = 115;
  /** RegularExpression Id. */
  int K_TOP = 116;
  /** RegularExpression Id. */
  int K_CACHE = 117;
  /** RegularExpression Id. */
  int K_MEMORY = 118;
  /** RegularExpression Id. */
  int K_CACHED = 119;
  /** RegularExpression Id. */
  int K_TEMP = 120;
  /** RegularExpression Id. */
  int K_LOCAL = 121;
  /** RegularExpression Id. */
  int K_GLOBAL = 122;
  /** RegularExpression Id. */
  int K_TEMPORARY = 123;
  /** RegularExpression Id. */
  int K_SAVE = 124;
  /** RegularExpression Id. */
  int K_SPECIFICATION = 125;
  /** RegularExpression Id. */
  int K_LIMIT = 126;
  /** RegularExpression Id. */
  int K_OFFSET = 127;
  /** RegularExpression Id. */
  int K_SAMPLE_SIZE = 128;
  /** RegularExpression Id. */
  int K_FOR = 129;
  /** RegularExpression Id. */
  int K_TRUE = 130;
  /** RegularExpression Id. */
  int K_FALSE = 131;
  /** RegularExpression Id. */
  int K_YES = 132;
  /** RegularExpression Id. */
  int K_NO = 133;
  /** RegularExpression Id. */
  int K_EXPLAIN = 134;
  /** RegularExpression Id. */
  int K_PLAN = 135;
  /** RegularExpression Id. */
  int K_ANALYZE = 136;
  /** RegularExpression Id. */
  int K_CASE_WHEN = 137;
  /** RegularExpression Id. */
  int K_IIF = 138;
  /** RegularExpression Id. */
  int K_NOCHECK = 139;
  /** RegularExpression Id. */
  int K_RELOAD = 140;
  /** RegularExpression Id. */
  int S_NUMBER = 141;
  /** RegularExpression Id. */
  int S_INTEGER = 142;
  /** RegularExpression Id. */
  int FLOAT = 143;
  /** RegularExpression Id. */
  int INTEGER = 144;
  /** RegularExpression Id. */
  int DIGIT = 145;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 146;
  /** RegularExpression Id. */
  int LETTER = 147;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 148;
  /** RegularExpression Id. */
  int S_CHAR_LITERAL = 149;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 150;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinComment = 1;
  /** Lexical state. */
  int LineComment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"/*\"",
    "\"--\"",
    "\"*/\"",
    "<token of kind 8>",
    "<token of kind 9>",
    "<token of kind 10>",
    "\"ALL\"",
    "\"ALIAS\"",
    "\"ALTER\"",
    "\"ADD\"",
    "\"ANALIZE\"",
    "\"AND\"",
    "\"ANY\"",
    "\"AS\"",
    "\"ASC\"",
    "\"BETWEEN\"",
    "\"BY\"",
    "\"CALL\"",
    "\"CASCADE\"",
    "\"CASE\"",
    "\"CAST\"",
    "\"CHAINED\"",
    "\"CHECK\"",
    "\"CLUSTER\"",
    "\"CLUSTERED\"",
    "\"COLLATE\"",
    "\"COLUMN\"",
    "\"COLUMNS\"",
    "\"COMPUTE\"",
    "\"CONSTRAINT\"",
    "\"CONSUMERS\"",
    "\"CREATE\"",
    "\"CROSS\"",
    "\"DATABASE\"",
    "\"DATEADD\"",
    "\"DATEDIFF\"",
    "\"DEFAULT\"",
    "\"DELETE\"",
    "\"DESC\"",
    "\"DESCRIPTOR\"",
    "\"DISTINCT\"",
    "\"DROP\"",
    "\"ELSE\"",
    "\"END\"",
    "\"ESTIMATE\"",
    "\"EXCEPT\"",
    "\"EXEC\"",
    "\"EXECUTE\"",
    "\"EXISTS\"",
    "\"FOREIGN\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"FULLSCAN\"",
    "\"GO\"",
    "\"GROUP\"",
    "\"HAVING\"",
    "\"IMMEDIATE\"",
    "\"IF\"",
    "\"IN\"",
    "\"INDEX\"",
    "\"INDICATOR\"",
    "\"INNER\"",
    "\"INSERT\"",
    "\"INTO\"",
    "\"IS\"",
    "\"JOIN\"",
    "\"KEY\"",
    "\"LIKE\"",
    "\"LIST\"",
    "\"LEFT\"",
    "\"LOCK\"",
    "\"MINUS\"",
    "\"NATURAL\"",
    "\"NONCLUSTERED\"",
    "\"NOT\"",
    "\"NORECOMPUTE\"",
    "\"NULL\"",
    "\"ON\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"OUT\"",
    "\"OUTER\"",
    "\"PARTITION\"",
    "\"PERCENT\"",
    "\"PRIMARY\"",
    "\"RECOMPILE\"",
    "\"REFERENCES\"",
    "\"RESAMPLE\"",
    "\"RIGHT\"",
    "\"ROWS\"",
    "\"SAMPLE\"",
    "\"SELECT\"",
    "\"SET\"",
    "\"SHUTDOWN\"",
    "\"SOME\"",
    "\"STATISTICS\"",
    "\"STRUCTURE\"",
    "\"TABLE\"",
    "\"THEN\"",
    "\"TO\"",
    "\"UNION\"",
    "\"UNIQUE\"",
    "\"UNLOCK\"",
    "\"UPDATE\"",
    "\"USING\"",
    "\"VALIDATE\"",
    "\"VALUES\"",
    "\"VIEW\"",
    "\"WHEN\"",
    "\"WHERE\"",
    "\"WITH\"",
    "\"TOP\"",
    "\"CACHE\"",
    "\"MEMORY\"",
    "\"CACHED\"",
    "\"TEMP\"",
    "\"LOCAL\"",
    "\"GLOBAL\"",
    "\"TEMPORARY\"",
    "\"SAVE\"",
    "\"SPECIFICATION\"",
    "\"LIMIT\"",
    "\"OFFSET\"",
    "\"SAMPLE_SIZE\"",
    "\"FOR\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"YES\"",
    "\"NO\"",
    "\"EXPLAIN\"",
    "\"PLAN\"",
    "\"ANALYZE\"",
    "\"CASEWHEN\"",
    "\"IIF\"",
    "\"NOCHECK\"",
    "\"RELOAD\"",
    "<S_NUMBER>",
    "<S_INTEGER>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "\";\"",
    "\",\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\"#\"",
    "\"<>\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"+\"",
    "\"-\"",
    "\"||\"",
    "\"/\"",
    "\"**\"",
    "\"%\"",
    "\"@\"",
    "\":\"",
  };

}
