package com.relationaljunction.jdbc.common.h2;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Set;

import org.h2.jdbc.JdbcPreparedStatement;
import org.h2.jdbc.JdbcResultSet;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.relationaljunction.jdbc.common.h2.sql.H2PreparedStatementListener;
import com.relationaljunction.jdbc.common.h2.sql.SQLCommand;

public class CommonPreparedStatement2 extends CommonStatement2 implements
        PreparedStatement, H2PreparedStatementListener {
   private final Logger log = LoggerFactory.getLogger("CommonPreparedStatement2");

   private final String quotedSql;
   private SQLCommand command = null;
   private final Set<String> realTablesUsed;

   public CommonPreparedStatement2(CommonConnection2 conn,
                                   String sourceSql,
                                   int resultSetType,
                                   int resultSetConcurrency,
                                   int resultSetHoldability,
                                   int autoGeneratedKeys,
                                   int[] columnIndexes,
                                   String[] columnNames) throws SQLException {
      super(conn);

      // parse a sql to get tables that should be loaded to H2
      try {
         command = SQLCommand.parseSQLCommand(sourceSql);
      } catch (Exception ex) {
         throw new SQLException("Can't parse SQL query '" + sourceSql + "'. Error was " + ex.getMessage() +
                 ". Check the following points in your SQL syntax:\n" +
                 "1) column using an SQL reserved word as a name or containing spaces and other delimiters (-,.,;,:, etc) must be quoted in double quotes in a query, e.g.: SELECT \"DATE\", \"My integer-column\" FROM \"test.txt\"" + "\n" +
                 "2) To use single quotes (') within a string constant you should duplicate them, e.g.: SELECT 'a''bcd''efgh'", "42001");
      }

      com.relationaljunction.utils.OtherUtils.writeLogInfo(log,
              "preparing a statement for the query '" +
                      sourceSql + "'");

      this.quotedSql = command.getSqlText();
      realTablesUsed = loadTablesFromStore(command.getTablesUsed());

      if (autoGeneratedKeys != -1)
         h2Stat = conn.getH2Connection().prepareStatement(this.
                 quotedSql, autoGeneratedKeys);
      else if (columnIndexes != null)
         h2Stat = conn.getH2Connection().prepareStatement(this.
                 quotedSql, columnIndexes);
      else if (columnNames != null)
         h2Stat = conn.getH2Connection().prepareStatement(this.
                 quotedSql, columnNames);
      else if (resultSetHoldability != -1)
         h2Stat = conn.getH2Connection().prepareStatement(this.
                 quotedSql, resultSetType, resultSetConcurrency, resultSetHoldability);
      else if (resultSetConcurrency != -1)
         h2Stat = conn.getH2Connection().prepareStatement(this.
                 quotedSql, resultSetType, resultSetConcurrency);
      else
         h2Stat = conn.getH2Connection().prepareStatement(this.
                 quotedSql);

      init();

      ((JdbcPreparedStatement) h2Stat).setListener(this);
   }

   public void beginOperation() {
      conn.getCacheTableManager().beginOperation(command);
   }
   
   @Override
   public void endOperation(long updateCount) {
       conn.getCacheTableManager().endOperation(command, updateCount);

       com.relationaljunction.utils.OtherUtils.writeLogInfo(log, "execute update: " + quotedSql);
       
   }


   public void addBatch() throws SQLException {
      checkClosed();
      ((JdbcPreparedStatement) h2Stat).addBatch();
   }

   public void clearBatch() throws SQLException {
      checkClosed();
      h2Stat.clearBatch();
   }

   public void clearParameters() throws SQLException {
      ((JdbcPreparedStatement) h2Stat).clearParameters();
   }

   public boolean execute() throws SQLException {
      checkClosed();

      com.relationaljunction.utils.OtherUtils.writeLogInfo(log,
              "Connection(" + conn.toString() +
                      ") -> PreparedStatement(" +
                      this +
                      ") -> execute(): sql=" +
                      quotedSql);

      if (command.getType() == SQLCommand.SELECT ||
              command.getType() == SQLCommand.EXPLAIN) {
         executeQuery();
         return true;
      } else {
         executeUpdate();
         return false;
      }
   }

   public int[] executeBatch() throws SQLException {
      checkClosed();

      int[] result = null;

//    synchronized (conn.getH2Connection()) {

      conn.getCacheTableManager().writeLockTables(command.getTablesUsed());
      try {
         result = h2Stat.executeBatch();

         if (conn.autoCommit)
            conn.commit(command.getTablesUsed());
      } catch (Exception ex) {
         if (conn.getAutoCommit())
            conn.getCacheTableManager().clearTransactionFlag(command);
         log.error("Error while executing a prepared batch. " +
                 ex.getMessage(), ex);
         throw conn.driver.createException("Error while executing a prepared batch. " +
                 ex.getMessage(), ex);
      } finally {
         conn.getCacheTableManager().writeUnlockTables(command.getTablesUsed());
      }

      // it is not required to call clearBatch() here,
      // since the current batch is already cleared by H2

//    } // synchronized

      return result;
   }

   public ResultSet executeQuery() throws SQLException {
      checkClosed();

      com.relationaljunction.utils.OtherUtils.writeLogInfo(log,
              "Connection(" + conn.toString() +
                      ") -> PreparedStatement(" +
                      this +
                      ") -> executeQuery(): sql=" +
                      quotedSql);

      //#######for registration###########
      r();
      //#################################

      if (command.getType() != SQLCommand.SELECT &&
              command.getType() != SQLCommand.EXPLAIN)
         throw conn.driver.createException(
                 "The executeQuery() method is only allowed for a query. " +
                         "Use execute() or executeUpdate() instead of executeQuery().");

//    synchronized (conn.getH2Connection()) {
      //#######for registration###########
      updateRecordsLoadedInfo();
      //#################################

      ResultSet rs = null;

      // lock tables for reading
      conn.cacheTableManager.readLockTables(realTablesUsed);

      com.relationaljunction.utils.OtherUtils.writeLogInfo(log, "execute the query: " + quotedSql + " directly in H2");

      try {
         rs = ((JdbcPreparedStatement) h2Stat).executeQuery();

         // set a wrapper connection to allow updating a result set.
         if (getResultSetConcurrency() == ResultSet.CONCUR_UPDATABLE) {
            ((JdbcResultSet) rs).setWrapperConnection(conn);
         }
      } catch (SQLException ex) {
         throw conn.driver.createException(
                 "Error while executing an SQL query. [H2 Database] " + ex.getMessage(),
                 ex.getSQLState(), ex);
      } finally {
         // unlock tables for reading
         conn.cacheTableManager.readUnlockTables(realTablesUsed);
      }

      com.relationaljunction.utils.OtherUtils.writeLogInfo(log,
              "end of executing the query: '" +
                      quotedSql +
                      "'");

      return rs;
//    } // synchronized
   }

   public int executeUpdate() throws SQLException {
      checkClosed();

      com.relationaljunction.utils.OtherUtils.writeLogInfo(log,
              "Connection(" + conn.toString() +
                      ") -> PreparedStatement(" +
                      this +
                      ") -> executeUpdate(): sql=" +
                      quotedSql);

      //#######for registration###########
      r();
      //#################################

      int updateCount = 0;

      if (command.getType() == SQLCommand.SELECT ||
              command.getType() == SQLCommand.EXPLAIN)
         throw conn.driver.createException(
                 "This method is not allowed for a SELECT query. " +
                         "Use executeQuery() instead of executeUpdate() for SELECT queries.");

//    synchronized (conn.getH2Connection()) {
      //#######for registration###########
      updateRecordsLoadedInfo();
      //#################################

      conn.getCacheTableManager().writeLockTables(command.getTablesUsed());
      try {
         try {
            com.relationaljunction.utils.OtherUtils.writeLogInfo(log,
                    "execute the prepared update directly in H2: '" +
                            quotedSql +
                            "'");

            updateCount = ((JdbcPreparedStatement) h2Stat).executeUpdate();
         } catch (SQLException ex) {
//	ex.printStackTrace();
            throw new SQLException("[H2 Database] " + ex.getMessage(),
                    ex.getSQLState());
         }

         if (conn.autoCommit)
            conn.commit(command.getTablesUsed());

//    } // synchronized

      } catch (Exception ex) {
         // error ocurred in a transaction

         if (conn.getAutoCommit()) {
            // just clear transaction flag for the table involved
            // rollback should be executed on the customer's side
            // if (autoCommit = false) this action is not required,
            // because a transaction goes in progress
            conn.getCacheTableManager().clearTransactionFlag(command);
         }

         log.error("Error while executing an SQL query. " +
                 ex.getMessage(), ex);
         throw conn.driver.createException("Error while executing an SQL query. " +
                 ex.getMessage(), ex);
      } finally {
         conn.getCacheTableManager().writeUnlockTables(command.getTablesUsed());
      }

      com.relationaljunction.utils.OtherUtils.writeLogInfo(log,
              "end of executing the prepared update. Row processed " +
                      updateCount);

      return updateCount;
   }

   public ResultSetMetaData getMetaData() throws SQLException {
      return ((JdbcPreparedStatement) h2Stat).getMetaData();
   }

   public ParameterMetaData getParameterMetaData() throws SQLException {
      return ((JdbcPreparedStatement) h2Stat).getParameterMetaData();
   }

   // ##### not allowed from Statement interface ####
   public void addBatch(String sql) throws SQLException {
      h2Stat.addBatch(sql);
   }

   public ResultSet executeQuery(String sql) throws SQLException {
      return h2Stat.executeQuery(sql);
   }

   public int executeUpdate(String sql, int autoGeneratedKeys) throws
           SQLException {
      return h2Stat.executeUpdate(sql,
              autoGeneratedKeys);
   }

   public int executeUpdate(String sql) throws SQLException {
      return h2Stat.executeUpdate(sql);
   }

   public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
      return h2Stat.executeUpdate(sql, columnIndexes);
   }

   public int executeUpdate(String sql, String[] columnNames) throws
           SQLException {
      return h2Stat.executeUpdate(sql, columnNames);
   }

   public boolean execute(String sql) throws SQLException {
      return h2Stat.execute(sql);
   }

   public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
      return h2Stat.execute(sql, autoGeneratedKeys);
   }

   public boolean execute(String sql, int[] columnIndexes) throws SQLException {
      return h2Stat.execute(sql, columnIndexes);
   }

   public boolean execute(String sql, String[] columnNames) throws SQLException {
      return h2Stat.execute(sql, columnNames);
   }

   // ##### setting methods of PreparedStatement ####

   public void setArray(int i, Array x) throws SQLException {
      ((JdbcPreparedStatement) h2Stat).setArray(i, x);
   }

   public void setAsciiStream(int parameterIndex, InputStream x, int length) throws
           SQLException {
      ((JdbcPreparedStatement) h2Stat).setAsciiStream(parameterIndex, x, length);
   }

   public void setBigDecimal(int parameterIndex, BigDecimal x) throws
           SQLException {
      ((JdbcPreparedStatement) h2Stat).setBigDecimal(parameterIndex, x);
   }

   public void setBinaryStream(int parameterIndex, InputStream x, int length) throws
           SQLException {
      ((JdbcPreparedStatement) h2Stat).setBinaryStream(parameterIndex, x, length);
   }

   public void setBlob(int i, Blob x) throws SQLException {
      ((JdbcPreparedStatement) h2Stat).setBlob(i, x);
   }

   public void setBoolean(int parameterIndex, boolean x) throws SQLException {
      ((JdbcPreparedStatement) h2Stat).setBoolean(parameterIndex, x);
   }

   public void setByte(int parameterIndex, byte x) throws SQLException {
      ((JdbcPreparedStatement) h2Stat).setByte(parameterIndex, x);
   }

   public void setBytes(int parameterIndex, byte[] x) throws SQLException {
      ((JdbcPreparedStatement) h2Stat).setBytes(parameterIndex, x);
   }

   public void setCharacterStream(int parameterIndex, Reader reader, int length) throws
           SQLException {
      ((JdbcPreparedStatement) h2Stat).setCharacterStream(parameterIndex, reader,
              length);
   }

   public void setClob(int i, Clob x) throws SQLException {
      ((JdbcPreparedStatement) h2Stat).setClob(i, x);
   }

   public void setCursorName(String name) throws SQLException {
      h2Stat.setCursorName(name);
   }

   public void setDate(int parameterIndex, Date x, Calendar cal) throws
           SQLException {
      ((JdbcPreparedStatement) h2Stat).setDate(parameterIndex, x, cal);
   }

   public void setDate(int parameterIndex, Date x) throws SQLException {
      ((JdbcPreparedStatement) h2Stat).setDate(parameterIndex, x);
   }

   public void setDouble(int parameterIndex, double x) throws SQLException {
      ((JdbcPreparedStatement) h2Stat).setDouble(parameterIndex, x);
   }

   public void setEscapeProcessing(boolean enable) throws SQLException {
      h2Stat.setEscapeProcessing(enable);
   }

   public void setFetchDirection(int direction) throws SQLException {
      h2Stat.setFetchDirection(direction);
   }

   public void setFetchSize(int rows) throws SQLException {
      h2Stat.setFetchSize(rows);
   }

   public void setFloat(int parameterIndex, float x) throws SQLException {
      ((JdbcPreparedStatement) h2Stat).setFloat(parameterIndex, x);
   }

   public void setInt(int parameterIndex, int x) throws SQLException {
      ((JdbcPreparedStatement) h2Stat).setInt(parameterIndex, x);
   }

   public void setLong(int parameterIndex, long x) throws SQLException {
      ((JdbcPreparedStatement) h2Stat).setLong(parameterIndex, x);
   }

   public void setNull(int paramIndex, int sqlType, String typeName) throws
           SQLException {
      ((JdbcPreparedStatement) h2Stat).setNull(paramIndex, sqlType, typeName);
   }

   public void setNull(int parameterIndex, int sqlType) throws SQLException {
      ((JdbcPreparedStatement) h2Stat).setNull(parameterIndex, sqlType);
   }

   public void setObject(int parameterIndex, Object x, int targetSqlType,
                         int scale) throws SQLException {
      ((JdbcPreparedStatement) h2Stat).setObject(parameterIndex, x, targetSqlType,
              scale);
   }

   public void setObject(int parameterIndex, Object x) throws SQLException {
      ((JdbcPreparedStatement) h2Stat).setObject(parameterIndex, x);
   }

   public void setObject(int parameterIndex, Object x, int targetSqlType) throws
           SQLException {
      ((JdbcPreparedStatement) h2Stat).setObject(parameterIndex, x, targetSqlType);
   }

   public void setRef(int i, Ref x) throws SQLException {
      ((JdbcPreparedStatement) h2Stat).setRef(i, x);
   }

   public void setShort(int parameterIndex, short x) throws SQLException {
      ((JdbcPreparedStatement) h2Stat).setShort(parameterIndex, x);
   }

   public void setString(int parameterIndex, String x) throws SQLException {
      ((JdbcPreparedStatement) h2Stat).setString(parameterIndex, x);
   }

   public void setTime(int parameterIndex, Time x) throws SQLException {
      ((JdbcPreparedStatement) h2Stat).setTime(parameterIndex, x);
   }

   public void setTime(int parameterIndex, Time x, Calendar cal) throws
           SQLException {
      ((JdbcPreparedStatement) h2Stat).setTime(parameterIndex, x, cal);
   }

   public void setTimestamp(int parameterIndex, Timestamp x) throws SQLException {
      ((JdbcPreparedStatement) h2Stat).setTimestamp(parameterIndex, x);
   }

   public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws
           SQLException {
      ((JdbcPreparedStatement) h2Stat).setTimestamp(parameterIndex, x, cal);
   }

   public void setURL(int parameterIndex, URL x) throws SQLException {
      ((JdbcPreparedStatement) h2Stat).setURL(parameterIndex, x);
   }

   public void setUnicodeStream(int parameterIndex, InputStream x, int length) throws
           SQLException {
      ((JdbcPreparedStatement) h2Stat).setUnicodeStream(parameterIndex, x, length);
   }

   // --- JDK 1.6 ---

   public void setAsciiStream(int parameterIndex, InputStream x) throws SQLException {
      //To change body of implemented methods use File | Settings | File Templates.
   }

   public void setRowId(int parameterIndex, RowId x) throws SQLException {
      //To change body of implemented methods use File | Settings | File Templates.
   }

   public void setNString(int parameterIndex, String value) throws SQLException {
      //To change body of implemented methods use File | Settings | File Templates.
   }

   public void setNCharacterStream(int parameterIndex, Reader value, long length) throws SQLException {
      //To change body of implemented methods use File | Settings | File Templates.
   }

   public void setNClob(int parameterIndex, NClob value) throws SQLException {
      //To change body of implemented methods use File | Settings | File Templates.
   }

   public void setClob(int parameterIndex, Reader reader, long length) throws SQLException {
      //To change body of implemented methods use File | Settings | File Templates.
   }

   public void setBlob(int parameterIndex, InputStream inputStream, long length) throws SQLException {
      //To change body of implemented methods use File | Settings | File Templates.
   }

   public void setNClob(int parameterIndex, Reader reader, long length) throws SQLException {
      //To change body of implemented methods use File | Settings | File Templates.
   }

   public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws SQLException {
      //To change body of implemented methods use File | Settings | File Templates.
   }

   public void setAsciiStream(int parameterIndex, InputStream x, long length) throws SQLException {
      //To change body of implemented methods use File | Settings | File Templates.
   }

   public void setBinaryStream(int parameterIndex, InputStream x, long length) throws SQLException {
      //To change body of implemented methods use File | Settings | File Templates.
   }

   public void setCharacterStream(int parameterIndex, Reader reader, long length) throws SQLException {
      //To change body of implemented methods use File | Settings | File Templates.
   }

   public void setBinaryStream(int parameterIndex, InputStream x) throws SQLException {
      //To change body of implemented methods use File | Settings | File Templates.
   }

   public void setCharacterStream(int parameterIndex, Reader reader) throws SQLException {
      //To change body of implemented methods use File | Settings | File Templates.
   }

   public void setNCharacterStream(int parameterIndex, Reader value) throws SQLException {
      //To change body of implemented methods use File | Settings | File Templates.
   }

   public void setClob(int parameterIndex, Reader reader) throws SQLException {
      //To change body of implemented methods use File | Settings | File Templates.
   }

   public void setBlob(int parameterIndex, InputStream inputStream) throws SQLException {
      //To change body of implemented methods use File | Settings | File Templates.
   }

   public void setNClob(int parameterIndex, Reader reader) throws SQLException {
      //To change body of implemented methods use File | Settings | File Templates.
   }
}
